config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  get 'pages/home'

  devise_for :users

  namespace :admin do
    resources :speakers
    resources :playlists
    resources :media
    resources :cues
  end
end

app/views/admin/templates/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-fluid">
    <%= link_to t('baheth'), root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t('.manage_speakers'), admin_speakers_path, class: "nav-link #{'active' if controller_name == 'speakers'}" %>
        </li>
        <li class="nav-item">
          <%= link_to t('.manage_playlists'), admin_playlists_path, class: "nav-link #{'active' if controller_name == 'playlists'}" %>
        </li>
        <li class="nav-item">
          <%= link_to t('.manage_media'), admin_media_path, class: "nav-link #{'active' if controller_name == 'media'}" %>
        </li>
        <li class="nav-item">
          <%= link_to t('.manage_cues'), admin_cues_path, class: "nav-link #{'active' if controller_name == 'cues'}" %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item d-flex">
          <%= link_to t('sign_out'), destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: 'nav-link pe-0' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/templates/_edit.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <span class="fs-4"><%= t(".#{controller_name.singularize}") %></span>
      </div>

      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/templates/_index.html.erb
<div class="row">
  <div class="col">
    <%= form_with url: { controller: "admin/#{controller_name}", action: :index }, method: :get, class: 'input-group mb-3' do |f| %>
      <%= f.label :query, t(".#{controller_name}.search_label"), class: 'form-label' %>
      <div class="input-group">
        <%= f.search_field :query, class: 'form-control', value: params[:query] %>
        <%= f.submit t('search'), class: 'btn btn-outline-secondary', name: nil %>
      </div>
    <% end %>

    <div id="<%= controller_name %>">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span class="fs-4"><%= t(".#{controller_name}.title") %></span>
          <%= link_to '<i class="bi bi-plus-circle-fill"></i>'.html_safe, { controller: "admin/#{controller_name}", action: :new }, class: 'btn btn-sm btn-outline-primary' %>
        </div>

        <div class="card-body p-0">
          <div class="table-responsive">
            <table class="table table-hover mb-0 text-nowrap">
              <thead>
                <tr>
                  <% t(".#{controller_name}.attributes").each do |attribute| %>
                    <th scope="col"><%= t("attributes.#{attribute}") %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% records.each do |record| %>
                  <%= render "#{controller_name.singularize}_row", record: record %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div class="card-footer">
          <%= t(".#{controller_name}.count") %>: <%= controller_name.classify.constantize.count %>
        </div>
      </div>
    </div>

    <%= render 'templates/pagy_nav', pagy: pagy %>
  </div>
</div>

app/views/admin/templates/_new.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <span class="fs-4"><%= t(".#{controller_name.singularize}") %></span>
      </div>

      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>