config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  get 'pages/home'

  devise_for :users

  namespace :admin do
    resources :speakers
    resources :playlists
    resources :media
    resources :cues
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  include MeiliSearch::Rails

  extend Pagy::Meilisearch
  ActiveRecord_Relation.include Pagy::Meilisearch

  belongs_to :user
  has_and_belongs_to_many :speakers # rubocop:disable Rails/HasAndBelongsToMany
  has_many :media, dependent: :destroy
  has_many :cues, through: :media

  validates :title, :speakers, presence: true
  validates :link, url: { allow_blank: true, schemes: ['https'] }

  validate :one_speaker_at_least?

  acts_as_taggable

  meilisearch do
    attribute :title, :description

    attribute :tags do
      tag_list.join('، ')
    end
  end

  def one_speaker_at_least?
    return unless speakers.empty?

    errors.add(:speakers, 'need one speaker at least')
  end
end

app/controllers/admin/playlists_controller.rb
module Admin
  class PlaylistsController < AdminController
    INCLUDES = %i[taggings speakers user].freeze

    include Pagy::Backend

    load_and_authorize_resource
    skip_load_resource only: :index

    # GET /admin/playlists or /admin/playlists.json
    def index
      if params[:query].present?
        search
      elsif params[:tag].present?
        tag_filter
      else
        @pagy, @playlists = pagy(Playlist.accessible_by(current_ability).includes(INCLUDES).order(:id))
      end
    end

    # GET /admin/playlists/1 or /admin/playlists/1.json
    def show; end

    # GET /admin/playlists/new
    def new; end

    # GET /admin/playlists/1/edit
    def edit; end

    # POST /admin/playlists or /admin/playlists.json
    def create
      @playlist.user = current_user

      respond_to do |format|
        if @playlist.save
          format.html { redirect_to admin_playlist_url(@playlist), notice: 'Playlist was successfully created.' }
          format.json { render :show, status: :created, location: @playlist }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/playlists/1 or /admin/playlists/1.json
    def update
      respond_to do |format|
        if @playlist.update(playlist_params)
          format.html { redirect_to admin_playlist_url(@playlist), notice: 'Playlist was successfully updated.' }
          format.json { render :show, status: :ok, location: @playlist }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/playlists/1 or /admin/playlists/1.json
    def destroy
      @playlist.destroy

      respond_to do |format|
        format.html { redirect_to admin_playlists_url, notice: 'Playlist was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def search
      playlists = Playlist.accessible_by(current_ability).includes(INCLUDES).pagy_search(params[:query])
      @pagy, @playlists = pagy_meilisearch(playlists)
    end

    def tag_filter
      playlists = Playlist.accessible_by(current_ability).tagged_with(params[:tag]).includes(INCLUDES).order(:id)
      @pagy, @playlists = pagy(playlists)
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:title, :description, :link, :tag_list, :hidden, speaker_ids: [])
    end
  end
end

app/helpers/admin/playlists_helper.rb
module Admin
  module PlaylistsHelper
    include Pagy::Frontend
  end
end

app/views/admin/playlists/_form.html.erb
<%= simple_form_for(@playlist, url: @playlist.persisted? ? admin_playlist_path : admin_playlists_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :link %>
    <%= f.input :tag_list, input_html: { value: f.object.tag_list.join(t('joiner')) } %>
    <%= f.input :hidden %>
    <%= f.association :speakers %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/admin/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card overflow-hidden">
        <div class="card-body">
          <div class="d-flex justify-content-between align-middle">
            <div>
              <h5 class="card-title"><i class="bi bi-collection-play-fill"></i> <%= playlist.title %></h5>
              <span class="card-subtitle mb-2 text-wrap text-muted"><%= playlist.description %></span>
            </div>

            <div class="text-nowrap">
              <%= link_to '<i class="bi bi-box-arrow-up-left"></i>'.html_safe, playlist.link, class: 'btn btn-sm btn-outline-primary', target: '_blank' %>
              <%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_playlist_path(playlist), class: 'btn btn-sm btn-outline-success' %>
              <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
                admin_playlist_path(playlist),
                method: :delete,
                data: {
                  confirm: t('are_you_sure'),
                  turbo_method: :delete,
                  turbo_confirm: t('are_you_sure')
                },
                class: 'btn btn-sm btn-outline-danger' %>
            </div>
          </div>

          <hr style="margin-right: -1rem; margin-left: -1rem;">

          <div class="row">
            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.tag_list') %></p>
              <p><%= tags_to_links(playlist).join(t('joiner')).html_safe %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_by') %></p>
              <p><%= playlist.user.name %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_at') %></p>
              <p><%= local_time playlist.created_at, :long %></p>
            </div>

            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.appears') %></p>
              <p><%= (playlist.hidden ? '<i class="bi bi-x-circle-fill text-danger"></i>' : '<i class="bi bi-check-circle-fill text-success"></i>').html_safe %></p>

              <p class="mb-0 text-muted"><%= t('attributes.cues') %></p>
              <p><%= playlist.cues.count %></p>

              <p class="mb-0 text-muted"><%= t('attributes.updated_at') %></p>
              <p><%= local_time playlist.updated_at, :long %></p>
            </div>
          </div>

          <div class="row mb-3">
            <div class="col">
              <p class="text-muted"><%= t('attributes.speakers') %> (<%= playlist.speakers.count %>)</p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.speakers.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% playlist.speakers.includes(%i[taggings user]).each do |speaker| %>
                      <%= render 'admin/speakers/speaker_row', record: speaker %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p class="text-muted"><%= t('attributes.media') %> (<%= playlist.media.count %>)</p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.media.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% playlist.media.includes([{ transcript_txt_attachment: :blob }, :taggings, :speakers, :user]).each do |medium| %>
                      <%= render 'admin/media/medium_row', record: medium %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/playlists/_playlist_row.html.erb
<tr class="align-middle">
  <th scope="row"><%= record.id %></th>
  <td><%= link_to record.title, admin_playlist_path(record) %></td>
  <td><%= link_to '<i class="bi bi-box-arrow-up-left"></i>'.html_safe, record.link, class: 'btn btn-sm btn-outline-primary', target: '_blank' %></td>
  <td><%= tags_to_links(record).join(t('joiner')).html_safe %></td>
  <td><%= (record.hidden ? '<i class="bi bi-x-circle-fill text-danger fs-4"></i>' : '<i class="bi bi-check-circle-fill text-success fs-4"></i>').html_safe %></td>
  <td><%= speakers_to_links(record.speakers).join(t('joiner')).html_safe %></td>
  <td><%= record.user.name %></td>
  <td><%= local_time record.created_at, :long %></td>
  <td><%= local_time record.updated_at, :long %></td>
  <td><%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_playlist_path(record), class: 'btn btn-sm btn-outline-success' %></td>
  <td>
    <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
      admin_playlist_path(record),
      method: :delete,
      data: {
        confirm: t('are_you_sure'),
        turbo_method: :delete,
        turbo_confirm: t('are_you_sure')
      },
      class: 'btn btn-sm btn-outline-danger' %>
  </td>
</tr>

app/views/admin/playlists/edit.html.erb
<%= render 'admin/templates/edit' %>

app/views/admin/playlists/index.html.erb
<%= render 'admin/templates/index', records: @playlists, pagy: @pagy %>

app/views/admin/playlists/new.html.erb
<%= render 'admin/templates/new' %>

app/views/admin/playlists/show.html.erb
<%= render @playlist %>