config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  get 'pages/home'

  devise_for :users

  namespace :admin do
    resources :speakers
    resources :playlists
    resources :media
    resources :cues
  end
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  include MeiliSearch::Rails

  extend Pagy::Meilisearch
  ActiveRecord_Relation.include Pagy::Meilisearch

  belongs_to :user
  has_and_belongs_to_many :playlists # rubocop:disable Rails/HasAndBelongsToMany
  has_many :media, through: :playlists
  has_many :cues, through: :media

  validates :name, presence: true

  acts_as_taggable

  meilisearch do
    attribute :name, :description

    attribute :tags do
      tag_list.join('، ')
    end
  end
end

app/controllers/admin/speakers_controller.rb
module Admin
  class SpeakersController < AdminController
    INCLUDES = %i[taggings user].freeze

    include Pagy::Backend

    load_and_authorize_resource
    skip_load_resource only: :index

    # GET /admin/speakers or /admin/speakers.json
    def index
      if params[:query].present?
        search
      elsif params[:tag].present?
        tag_filter
      else
        @pagy, @speakers = pagy(Speaker.accessible_by(current_ability).includes(INCLUDES).order(:id))
      end
    end

    # GET /admin/speakers/1 or /admin/speakers/1.json
    def show; end

    # GET /admin/speakers/new
    def new; end

    # GET /admin/speakers/1/edit
    def edit; end

    # POST /admin/speakers or /admin/speakers.json
    def create
      @speaker.user = current_user

      respond_to do |format|
        if @speaker.save
          format.html { redirect_to admin_speaker_url(@speaker), notice: 'Speaker was successfully created.' }
          format.json { render :show, status: :created, location: @speaker }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @speaker.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/speakers/1 or /admin/speakers/1.json
    def update
      respond_to do |format|
        if @speaker.update(speaker_params)
          format.html { redirect_to admin_speaker_url(@speaker), notice: 'Speaker was successfully updated.' }
          format.json { render :show, status: :ok, location: @speaker }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @speaker.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/speakers/1 or /admin/speakers/1.json
    def destroy
      @speaker.destroy

      respond_to do |format|
        format.html { redirect_to admin_speakers_url, notice: 'Speaker was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def search
      speakers = Speaker.accessible_by(current_ability).includes(INCLUDES).pagy_search(params[:query])
      @pagy, @speakers = pagy_meilisearch(speakers)
    end

    def tag_filter
      speakers = Speaker.accessible_by(current_ability).tagged_with(params[:tag]).includes(INCLUDES).order(:id)
      @pagy, @speakers = pagy(speakers)
    end

    # Only allow a list of trusted parameters through.
    def speaker_params
      params.require(:speaker).permit(:name, :description, :tag_list, :hidden)
    end
  end
end

app/helpers/admin/speakers_helper.rb
module Admin
  module SpeakersHelper
    include Pagy::Frontend

    def speakers_to_links(speakers)
      speakers.map { |speaker| link_to(speaker.name, admin_speaker_path(speaker)) }
    end
  end
end

app/views/admin/speakers/_form.html.erb
<%= simple_form_for(@speaker, url: @speaker.persisted? ? admin_speaker_path : admin_speakers_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :tag_list, input_html: { value: f.object.tag_list.join(t('joiner')) } %>
    <%= f.input :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/admin/speakers/_speaker.html.erb
<div id="<%= dom_id speaker %>">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card overflow-hidden">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div>
              <h5 class="card-title"><i class="bi bi-person-circle"></i> <%= speaker.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= speaker.description %></h6>
            </div>

            <div class="text-nowrap">
              <%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_speaker_path(speaker), class: 'btn btn-sm btn-outline-success' %>
              <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
                admin_speaker_path(speaker),
                method: :delete,
                data: {
                  confirm: t('are_you_sure'),
                  turbo_method: :delete,
                  turbo_confirm: t('are_you_sure')
                },
                class: 'btn btn-sm btn-outline-danger' %>
            </div>
          </div>

          <hr style="margin-right: -1rem; margin-left: -1rem;">

          <div class="row">
            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.tag_list') %></p>
              <p><%= tags_to_links(speaker).join(t('joiner')).html_safe %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_by') %></p>
              <p><%= speaker.user.name %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_at') %></p>
              <p><%= local_time speaker.created_at, :long %></p>
            </div>

            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.appears') %></p>
              <p><%= (speaker.hidden ? '<i class="bi bi-x-circle-fill text-danger"></i>' : '<i class="bi bi-check-circle-fill text-success"></i>').html_safe %></p>

              <p class="mb-0 text-muted"><%= t('attributes.cues') %></p>
              <p><%= speaker.cues.count %></p>

              <p class="mb-0 text-muted"><%= t('attributes.updated_at') %></p>
              <p><%= local_time speaker.updated_at, :long %></p>
            </div>
          </div>

          <div class="row mb-3">
            <div class="col">
              <p class="text-muted"><%= t('attributes.playlists') %> (<%= speaker.playlists.count %>)</p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.playlists.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% speaker.playlists.includes(%i[taggings speakers user]).each do |playlist| %>
                      <%= render 'admin/playlists/playlist_row', record: playlist %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p class="text-muted"><%= t('attributes.media') %> (<%= speaker.media.count %>)</p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.media.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% speaker.media.includes([{ transcript_txt_attachment: :blob }, :taggings, :playlist, :speakers, :user]).each do |medium| %>
                      <%= render 'admin/media/medium_row', record: medium %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/speakers/_speaker_row.html.erb
<tr class="align-middle">
  <th scope="row"><%= record.id %></th>
  <td><%= link_to record.name, admin_speaker_path(record) %></td>
  <td><%= tags_to_links(record).join(t('joiner')).html_safe %></td>
  <td><%= (record.hidden ? '<i class="bi bi-x-circle-fill text-danger fs-4"></i>' : '<i class="bi bi-check-circle-fill text-success fs-4"></i>').html_safe %></td>
  <td><%= record.user.name %></td>
  <td><%= local_time record.created_at, :long %></td>
  <td><%= local_time record.updated_at, :long %></td>
  <td><%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_speaker_path(record), class: 'btn btn-sm btn-outline-success' %></td>
  <td>
    <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
      admin_speaker_path(record),
      method: :delete,
      data: {
        confirm: t('are_you_sure'),
        turbo_method: :delete,
        turbo_confirm: t('are_you_sure')
      },
      class: 'btn btn-sm btn-outline-danger' %>
  </td>
</tr>

app/views/admin/speakers/edit.html.erb
<%= render 'admin/templates/edit' %>

app/views/admin/speakers/index.html.erb
<%= render 'admin/templates/index', records: @speakers, pagy: @pagy %>

app/views/admin/speakers/new.html.erb
<%= render 'admin/templates/new' %>

app/views/admin/speakers/show.html.erb
<%= render @speaker %>