config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  get 'pages/home'

  devise_for :users

  namespace :admin do
    resources :speakers
    resources :playlists
    resources :media
    resources :cues
  end
end

app/models/cue.rb
class Cue < ApplicationRecord
  include MeiliSearch::Rails

  extend Pagy::Meilisearch
  ActiveRecord_Relation.include Pagy::Meilisearch

  belongs_to :user
  belongs_to :medium
  has_one :playlist, through: :medium
  has_many :speakers, through: :playlist

  delegate :id, to: :playlist, prefix: true

  validates :content, :start_time, :end_time, presence: true
  validates :start_time, numericality: { greater_than_or_equal: 0 }
  validates :end_time, numericality: { greater_than: :start_time }

  meilisearch do
    attribute :content
  end

  def truncated_content(content_limit = 25)
    content.size > content_limit ? "#{content[0..content_limit]}..." : content
  end

  def previous_cue
    medium.cues.select { |cue| cue.start_time < start_time }
          .min_by { |cue| start_time - cue.start_time }
  end

  def next_cue
    medium.cues.select { |cue| cue.start_time > start_time }
          .min_by { |cue| cue.start_time - start_time }
  end
end

app/controllers/admin/cues_controller.rb
module Admin
  class CuesController < AdminController
    INCLUDES = %i[medium playlist speakers user].freeze

    include Pagy::Backend

    before_action :sanitize_cue_params, only: %i[create update]

    load_and_authorize_resource
    skip_load_resource only: :index

    # GET /admin/cues or /admin/cues.json
    def index
      if params[:query].present?
        search
      elsif params[:tag].present?
        tag_filter
      else
        @pagy, @cues = pagy(Cue.accessible_by(current_ability).includes(INCLUDES).order(:id))
      end
    end

    # GET /admin/cues/1 or /admin/cues/1.json
    def show; end

    # GET /admin/cues/new
    def new; end

    # GET /admin/cues/1/edit
    def edit; end

    # POST /admin/cues or /admin/cues.json
    def create
      @cue.user = current_user

      respond_to do |format|
        if @cue.save
          format.html { redirect_to admin_cue_url(@cue), notice: 'Cue was successfully created.' }
          format.json { render :show, status: :created, location: @cue }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @cue.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/cues/1 or /admin/cues/1.json
    def update
      respond_to do |format|
        if @cue.update(cue_params)
          format.html { redirect_to admin_cue_url(@cue), notice: 'Cue was successfully updated.' }
          format.json { render :show, status: :ok, location: @cue }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @cue.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/cues/1 or /admin/cues/1.json
    def destroy
      @cue.destroy

      respond_to do |format|
        format.html { redirect_to admin_cues_url, notice: 'Cue was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def search
      cues = Cue.accessible_by(current_ability).includes(INCLUDES).pagy_search(params[:query])
      @pagy, @cues = pagy_meilisearch(cues)
    end

    def tag_filter
      cues = Cue.accessible_by(current_ability).tagged_with(params[:tag]).includes(INCLUDES).order(:id)
      @pagy, @cues = pagy(cues)
    end

    def sanitize_cue_params
      params[:cue][:start_time] = params[:cue][:start_time].to_i.seconds
      params[:cue][:end_time] = params[:cue][:end_time].to_i.seconds
    end

    # Only allow a list of trusted parameters through.
    def cue_params
      params.require(:cue).permit(:content, :start_time, :end_time, :hidden, :medium_id)
    end
  end
end

app/helpers/admin/cues_helper.rb
module Admin
  module CuesHelper
    include Pagy::Frontend

    def open_medium_button(cue)
      link_to(
        '<i class="bi bi-box-arrow-up-left"></i>'.html_safe,
        cue.medium.link_with_start_time(cue.start_time.to_i),
        class: 'btn btn-sm btn-outline-primary',
        target: '_blank',
        rel: 'noopener'
      )
    end

    def previous_cue_button(cue)
      previous_cue = cue.previous_cue

      if previous_cue
        link_to(
          '<i class="bi bi-arrow-right"></i>'.html_safe,
          admin_cue_path(previous_cue),
          class: 'btn btn-sm btn-outline-primary'
        )
      else
        ''
      end
    end

    def next_cue_button(cue)
      next_cue = cue.next_cue

      if next_cue
        link_to(
          '<i class="bi bi-arrow-left"></i>'.html_safe,
          admin_cue_path(next_cue),
          class: 'btn btn-sm btn-outline-primary'
        )
      else
        ''
      end
    end
  end
end

app/views/admin/cues/_cue.html.erb
<div id="<%= dom_id cue %>">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card overflow-hidden">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div>
              <h6 class="card-subtitle mb-2 text-muted"><%= cue.content %></h6>
            </div>

            <div class="text-nowrap">
              <%= open_medium_button(cue) %>
              <%= previous_cue_button(cue) %>
              <%= next_cue_button(cue) %>
              <%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_cue_path(cue), class: 'btn btn-sm btn-outline-success' %>
              <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
                admin_cue_path(cue),
                method: :delete,
                data: {
                  confirm: t('are_you_sure'),
                  turbo_method: :delete,
                  turbo_confirm: t('are_you_sure')
                },
                class: 'btn btn-sm btn-outline-danger' %>
            </div>
          </div>

          <hr style="margin-right: -1rem; margin-left: -1rem;">

          <div class="row">
            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.start_time') %></p>
              <p><%= seconds_to_time(cue.start_time) %></p>

              <p class="mb-0 text-muted"><%= t('attributes.appears') %></p>
              <p><%= (cue.hidden ? '<i class="bi bi-x-circle-fill text-danger"></i>' : '<i class="bi bi-check-circle-fill text-success"></i>').html_safe %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_at') %></p>
              <p><%= local_time cue.created_at, :long %></p>
            </div>

            <div class="col">
              <p class="mb-0 text-muted"><%= t('attributes.end_time') %></p>
              <p><%= seconds_to_time(cue.end_time) %></p>

              <p class="mb-0 text-muted"><%= t('attributes.created_by') %></p>
              <p><%= cue.user.name %></p>

              <p class="mb-0 text-muted"><%= t('attributes.updated_at') %></p>
              <p><%= local_time cue.updated_at, :long %></p>
            </div>
          </div>

          <div class="row mb-3">
            <div class="col">
              <p class="text-muted"><%= t('attributes.speakers') %> (<%= cue.speakers.count %>)</p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.speakers.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% cue.speakers.includes(%i[taggings user]).each do |speaker| %>
                      <%= render 'admin/speakers/speaker_row', record: speaker %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <div class="row mb-3">
            <div class="col">
              <p class="text-muted"><%= t('attributes.playlist') %></p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.playlists.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render 'admin/playlists/playlist_row', record: cue.playlist %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p class="text-muted"><%= t('attributes.medium') %></p>

              <div class="table-responsive border border-bottom-0 rounded">
                <table class="table table-hover mb-0 text-nowrap align-middle">
                  <thead>
                    <tr>
                      <% t('admin.templates.index.media.attributes').each do |attribute| %>
                        <th scope="col"><%= t("attributes.#{attribute}") %></th>
                      <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render 'admin/media/medium_row', record: cue.medium %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/cues/_cue_row.html.erb
<tr class="align-middle">
  <th scope="row"><%= record.id %></th>
  <td><%= link_to record.truncated_content, admin_cue_path(record) %></td>
  <td><%= seconds_to_time(record.start_time) %></td>
  <td><%= seconds_to_time(record.end_time) %></td>
  <td><%= (record.hidden ? '<i class="bi bi-x-circle-fill text-danger fs-4"></i>' : '<i class="bi bi-check-circle-fill text-success fs-4"></i>').html_safe %></td>
  <td><%= link_to record.medium.title, admin_medium_path(record.medium) %></td>
  <td><%= link_to record.playlist.title, admin_playlist_path(record.playlist) %></td>
  <td><%= speakers_to_links(record.speakers).join(t('joiner')).html_safe %></td>
  <td><%= record.user.name %></td>
  <td><%= local_time record.created_at, :long %></td>
  <td><%= local_time record.updated_at, :long %></td>
  <td><%= open_medium_button(record) %></td>
  <td><%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_admin_cue_path(record), class: 'btn btn-sm btn-outline-success' %></td>
  <td>
    <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe,
      admin_cue_path(record),
      method: :delete,
      data: {
        confirm: t('are_you_sure'),
        turbo_method: :delete,
        turbo_confirm: t('are_you_sure')
      },
      class: 'btn btn-sm btn-outline-danger' %>
  </td>
</tr>

app/views/admin/cues/_form.html.erb
<%= simple_form_for(@cue, url: @cue.persisted? ? admin_cue_path : admin_cues_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :start_time, as: :integer %>
    <%= f.input :end_time, as: :integer %>
    <%= f.input :hidden %>
    <%= f.association :medium, prompt: :translate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/admin/cues/edit.html.erb
<%= render 'admin/templates/edit' %>

app/views/admin/cues/index.html.erb
<%= render 'admin/templates/index', records: @cues, pagy: @pagy %>

app/views/admin/cues/new.html.erb
<%= render 'admin/templates/new' %>

app/views/admin/cues/show.html.erb
<%= render @cue %>